- name: Add a new user named admin
  user:
    name: admin
    shell: /bin/bash
    password: "{{ admin_password }}"

- name: Add admin user to the sudoers
  copy:
    dest: "/etc/sudoers.d/admin"
    content: "admin  ALL=(ALL)  ALL"

- name: Deploy SSH Key
  authorized_key: 
    user: admin
    key: "{{ lookup('file', 'files/public_keys/id-rsa.pub') }}"
    state: present

- name: Disable Password Authentication
  lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes

- name: Disable Root Login
  lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin no"
        state=present
        backup=yes
  notify: 
  - restart ssh
