- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Disable SELinux
  selinux: state=disabled

- name: Disable SWAP 
  shell: |
    swapoff -a

- name: Disable SWAP in fstab 
  mount:
    name: swap
    fstype: swap
    state: absent
