- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Disable SELinux
  selinux: state=disabled

- name: Disable SWAP 
  shell: |
    swapoff -a

- name: Disable SWAP in fstab 
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
