---
- include_tasks: add-user.yml

- include_tasks: "{{ item }}"
  with_items: 
  - "disable-firewal-selinux.yml"
  - "ntp.yml"
  - "iscsid.yml"
  when: ansible_distribution == 'Rocky' or ansible_os_family == 'RedHat'
