cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local.:80

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
