---
k3s_version: v1.22.3+k3s1
# ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
dns_server: "8.8.8.8"